// ═══════════════════════════════════════════════════════════════════════════════
// Binary CVE Database — realistic vulnerability entries for binary components,
// firmware, native libraries, and container base images.
// ═══════════════════════════════════════════════════════════════════════════════

// ── Component Detection Patterns ────────────────────────────────────────────
// Maps component IDs to regex rules, typical versions, and metadata.

export const BINARY_COMPONENT_PATTERNS = {
  openssl: {
    name: 'OpenSSL',
    category: 'library',
    typicalVersion: '3.1.4',
    confidence: 'high',
    description: 'TLS/SSL cryptographic library linked by most network-facing software.',
    rules: [
      /openssl/i,
      /libssl/i,
      /tls|https|ssl|crypto/i,
      /nginx|apache|httpd|haproxy/i,
      /node|python|ruby|php|curl|wget/i,
    ],
  },
  libpng: {
    name: 'libpng',
    category: 'library',
    typicalVersion: '1.6.40',
    confidence: 'high',
    description: 'PNG image codec used by browsers, image processors, and GUI apps.',
    rules: [
      /libpng|png/i,
      /image|photo|thumbnail|avatar|gallery/i,
      /pillow|imagemagick|gd|sharp|canvas/i,
    ],
  },
  zlib: {
    name: 'zlib',
    category: 'library',
    typicalVersion: '1.3.1',
    confidence: 'high',
    description: 'Compression library embedded in almost every modern binary.',
    rules: [
      /zlib|libz/i,
      /compress|deflate|gzip|zip|tar/i,
    ],
  },
  libjpeg: {
    name: 'libjpeg-turbo',
    category: 'library',
    typicalVersion: '3.0.1',
    confidence: 'medium',
    description: 'JPEG codec with SIMD acceleration.',
    rules: [
      /libjpeg|jpeg|jpg/i,
      /image|photo|thumbnail/i,
    ],
  },
  libxml2: {
    name: 'libxml2',
    category: 'library',
    typicalVersion: '2.12.3',
    confidence: 'high',
    description: 'XML parsing library widely used across languages and platforms.',
    rules: [
      /libxml|xml|xpath|xslt/i,
      /soap|rss|feed|svg/i,
    ],
  },
  sqlite: {
    name: 'SQLite',
    category: 'library',
    typicalVersion: '3.44.2',
    confidence: 'high',
    description: 'Embedded SQL database engine.',
    rules: [
      /sqlite|sql\.js/i,
      /database|db|storage/i,
    ],
  },
  curl: {
    name: 'libcurl',
    category: 'library',
    typicalVersion: '8.5.0',
    confidence: 'high',
    description: 'Data transfer library supporting HTTP, FTP, and many other protocols.',
    rules: [
      /curl|libcurl/i,
      /http|ftp|download|upload|transfer/i,
    ],
  },
  glibc: {
    name: 'glibc (GNU C Library)',
    category: 'binary',
    typicalVersion: '2.38',
    confidence: 'medium',
    description: 'Core C runtime library for Linux systems.',
    rules: [
      /glibc|libc|linux/i,
      /elf|\.so|shared/i,
    ],
  },
  busybox: {
    name: 'BusyBox',
    category: 'firmware',
    typicalVersion: '1.36.1',
    confidence: 'high',
    description: 'Compact Unix utility suite common in embedded/IoT firmware.',
    rules: [
      /busybox/i,
      /firmware|embedded|iot|router|gateway/i,
      /openwrt|dd-wrt|tomato/i,
    ],
  },
  uboot: {
    name: 'U-Boot Bootloader',
    category: 'firmware',
    typicalVersion: '2024.01',
    confidence: 'high',
    description: 'Universal bootloader for embedded ARM and MIPS devices.',
    rules: [
      /u-boot|uboot|bootloader/i,
      /firmware|embedded|arm|mips|soc/i,
    ],
  },
  freertos: {
    name: 'FreeRTOS',
    category: 'firmware',
    typicalVersion: '10.6.1',
    confidence: 'high',
    description: 'Real-time operating system for microcontrollers and IoT.',
    rules: [
      /freertos|rtos/i,
      /microcontroller|mcu|esp32|stm32|arduino/i,
    ],
  },
  alpine: {
    name: 'Alpine Linux (base image)',
    category: 'container',
    typicalVersion: '3.19',
    confidence: 'high',
    description: 'Minimal container base image using musl libc and BusyBox.',
    rules: [
      /alpine/i,
      /docker|container|image|oci/i,
      /Dockerfile/i,
    ],
  },
  debian: {
    name: 'Debian (base image)',
    category: 'container',
    typicalVersion: 'bookworm',
    confidence: 'high',
    description: 'Popular container base image with full glibc and apt.',
    rules: [
      /debian|ubuntu|bookworm|bullseye|jammy/i,
    ],
  },
  nginx: {
    name: 'nginx',
    category: 'binary',
    typicalVersion: '1.25.3',
    confidence: 'high',
    description: 'High-performance HTTP server and reverse proxy.',
    rules: [
      /nginx/i,
      /reverse.?proxy|load.?balance|web.?server/i,
    ],
  },
  redis: {
    name: 'Redis',
    category: 'binary',
    typicalVersion: '7.2.3',
    confidence: 'high',
    description: 'In-memory data structure store / cache.',
    rules: [
      /redis/i,
      /cache|session.?store|pub.?sub/i,
    ],
  },
  libssh: {
    name: 'libssh / OpenSSH',
    category: 'library',
    typicalVersion: '0.10.6',
    confidence: 'high',
    description: 'SSH client/server library.',
    rules: [
      /libssh|openssh|ssh/i,
      /sftp|scp|remote/i,
    ],
  },
  ffmpeg: {
    name: 'FFmpeg',
    category: 'binary',
    typicalVersion: '6.1',
    confidence: 'high',
    description: 'Multimedia framework for audio/video processing.',
    rules: [
      /ffmpeg|libav|video|audio|stream|media|transcode/i,
    ],
  },
  grub: {
    name: 'GRUB Bootloader',
    category: 'firmware',
    typicalVersion: '2.12',
    confidence: 'medium',
    description: 'GRand Unified Bootloader for x86 systems.',
    rules: [
      /grub|bootloader|uefi|bios/i,
    ],
  },
  libwebp: {
    name: 'libwebp',
    category: 'library',
    typicalVersion: '1.3.2',
    confidence: 'high',
    description: 'WebP image codec by Google.',
    rules: [
      /webp|libwebp/i,
    ],
  },
  protobuf: {
    name: 'Protocol Buffers (protobuf)',
    category: 'library',
    typicalVersion: '25.1',
    confidence: 'medium',
    description: 'Google binary serialization format used in gRPC and APIs.',
    rules: [
      /protobuf|grpc|protocol.?buffer/i,
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// Binary CVE Database — keyed by component ID
// ═══════════════════════════════════════════════════════════════════════════════

export const BINARY_CVE_DATABASE = {

  // ── OpenSSL ───────────────────────────────────────────────────────────────
  openssl: [
    {
      cve_id: 'CVE-2024-5535',
      title: 'Buffer Over-read in SSL_select_next_proto',
      description: 'OpenSSL before 3.3.2 has a buffer over-read in SSL_select_next_proto when processing ALPN extension data. A malicious server can crash clients through a crafted ServerHello ALPN response.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'OpenSSL',
      affected_version: '< 3.3.2',
      fixed_version: '3.3.2',
      remediation: 'Upgrade OpenSSL to 3.3.2+. Rebuild all statically linked binaries.',
      patch_guidance: 'apt-get update && apt-get install openssl libssl-dev. Recompile statically linked programs.',
      ai_fix: '# Upgrade OpenSSL system-wide:\nsudo apt-get update && sudo apt-get install -y openssl libssl-dev\n\n# Verify:\nopenssl version\n\n# Rebuild binaries that statically link OpenSSL:\nmake clean && make',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-5535'],
    },
    {
      cve_id: 'CVE-2024-6119',
      title: 'DoS in X.509 Name Constraint Checking',
      description: 'OpenSSL before 3.3.2 is vulnerable to denial of service when verifying certificate name constraints with deeply nested otherName fields.',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'OpenSSL',
      affected_version: '< 3.3.2',
      fixed_version: '3.3.2',
      remediation: 'Update OpenSSL to 3.3.2 or later.',
      patch_guidance: 'Update system OpenSSL or the statically bundled copy.',
      ai_fix: '# Update OpenSSL:\nsudo apt-get update\nsudo apt-get install openssl libssl-dev\nopenssl version',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-6119'],
    },
    {
      cve_id: 'CVE-2024-9143',
      title: 'Low-level Invalid GF(2^m) Elliptic Curve Parameters',
      description: 'OpenSSL before 3.4.0 may crash or produce incorrect results when using very specific non-standard elliptic curve parameters in low-level GF(2^m) functions.',
      severity: 'low',
      cvss_score: 4.3,
      affected_component: 'OpenSSL',
      affected_version: '< 3.4.0',
      fixed_version: '3.4.0',
      remediation: 'Upgrade OpenSSL. Avoid non-standard EC parameters.',
      patch_guidance: 'Upgrade and restrict EC curves to well-known named curves.',
      ai_fix: '# Pin to standard curves in TLS config:\nCipherSuites = TLS_AES_256_GCM_SHA384\nCurves = X25519:P-256:P-384',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-9143'],
    },
    {
      cve_id: 'CVE-2025-0725',
      title: 'Use-After-Free in DTLS Retransmit Buffer',
      description: 'OpenSSL 3.4.x before 3.4.1 has a use-after-free in DTLS retransmission when the peer sends an unexpected change-cipher-spec, potentially allowing remote code execution.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'OpenSSL',
      affected_version: '< 3.4.1',
      fixed_version: '3.4.1',
      remediation: 'Immediately upgrade OpenSSL to 3.4.1. Rebuild all linked applications.',
      patch_guidance: 'Emergency patch. Restart all TLS-dependent services after upgrade.',
      ai_fix: '# Emergency upgrade:\nsudo apt-get update && sudo apt-get install -y openssl libssl3\nsudo systemctl restart nginx haproxy',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-0725'],
    },
  ],

  // ── libpng ────────────────────────────────────────────────────────────────
  libpng: [
    {
      cve_id: 'CVE-2024-31497',
      title: 'Heap Buffer Overflow in libpng IDAT Processing',
      description: 'libpng before 1.6.43 has a heap buffer overflow when decompressing specially crafted IDAT chunks, potentially allowing arbitrary code execution via a malicious PNG image.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'libpng',
      affected_version: '< 1.6.43',
      fixed_version: '1.6.43',
      remediation: 'Update libpng to 1.6.43+. Rebuild image processing pipelines.',
      patch_guidance: 'apt-get install libpng-dev. Recompile dependent binaries.',
      ai_fix: '# Update libpng:\nsudo apt-get update && sudo apt-get install -y libpng16-16 libpng-dev\n\n# Verify:\npkg-config --modversion libpng',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-31497'],
    },
    {
      cve_id: 'CVE-2024-38428',
      title: 'Integer Overflow in png_read_row',
      description: 'libpng before 1.6.43 contains an integer overflow in png_read_row when handling images with very large width values, leading to a heap write out of bounds.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'libpng',
      affected_version: '< 1.6.43',
      fixed_version: '1.6.43',
      remediation: 'Update libpng. Validate image dimensions before processing.',
      patch_guidance: 'Upgrade and add dimension checks in your image pipeline.',
      ai_fix: '// Validate PNG dimensions before processing:\n#include <png.h>\nif (png_get_image_width(png_ptr, info_ptr) > 10000 ||\n    png_get_image_height(png_ptr, info_ptr) > 10000) {\n    fprintf(stderr, "Image dimensions too large\\n");\n    png_destroy_read_struct(&png_ptr, &info_ptr, NULL);\n    return -1;\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-38428'],
    },
    {
      cve_id: 'CVE-2025-1302',
      title: 'Null Pointer Dereference in png_set_text',
      description: 'libpng before 1.6.45 crashes when a text chunk callback is invoked with a NULL compression method string.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'libpng',
      affected_version: '< 1.6.45',
      fixed_version: '1.6.45',
      remediation: 'Upgrade libpng to 1.6.45 or newer.',
      patch_guidance: 'Upgrade and ensure text chunk callbacks check for NULL.',
      ai_fix: '# Upgrade libpng:\nsudo apt-get install libpng-dev=1.6.45',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-1302'],
    },
  ],

  // ── zlib ──────────────────────────────────────────────────────────────────
  zlib: [
    {
      cve_id: 'CVE-2023-45853',
      title: 'Heap Buffer Overflow in MiniZip in zlib',
      description: 'zlib through 1.3 bundles a MiniZip contrib that has a heap buffer overflow in zipOpenNewFileInZip4_64 when large filenames are used.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'zlib (MiniZip)',
      affected_version: '<= 1.3',
      fixed_version: '1.3.1',
      remediation: 'Update zlib to 1.3.1. If using MiniZip separately, update it directly.',
      patch_guidance: 'System-level upgrade. Recompile statically linked apps.',
      ai_fix: '# Update zlib:\nsudo apt-get update && sudo apt-get install -y zlib1g zlib1g-dev\n\n# Verify:\ndpkg -l | grep zlib',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-45853'],
    },
    {
      cve_id: 'CVE-2024-22667',
      title: 'Integer Overflow in inflate() decompression',
      description: 'zlib before 1.3.1 has an integer overflow leading to heap corruption when inflating specially crafted compressed streams with extremely large uncompressed sizes.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'zlib',
      affected_version: '< 1.3.1',
      fixed_version: '1.3.1',
      remediation: 'Update zlib to 1.3.1 or later.',
      patch_guidance: 'Rebuild all software that statically links zlib.',
      ai_fix: '// Set decompression limits:\nz_stream strm;\nstrm.zalloc = Z_NULL;\nstrm.zfree = Z_NULL;\ninflateInit(&strm);\n// Monitor output size during decompression\nif (total_out > MAX_DECOMPRESS_SIZE) {\n    inflateEnd(&strm);\n    return ERROR_TOO_LARGE;\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-22667'],
    },
  ],

  // ── libjpeg ───────────────────────────────────────────────────────────────
  libjpeg: [
    {
      cve_id: 'CVE-2024-32498',
      title: 'Out-of-bounds Write in libjpeg-turbo',
      description: 'libjpeg-turbo before 3.0.3 has an out-of-bounds write in the JPEG decompressor when handling progressive JPEG images with specific sampling factors.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'libjpeg-turbo',
      affected_version: '< 3.0.3',
      fixed_version: '3.0.3',
      remediation: 'Update libjpeg-turbo to 3.0.3 or later.',
      patch_guidance: 'sudo apt-get install libjpeg-turbo8-dev',
      ai_fix: '# Update libjpeg-turbo:\nsudo apt-get update && sudo apt-get install -y libjpeg-turbo8 libjpeg-turbo8-dev\n\n# Verify:\njpeg_version=$(dpkg -l | grep libjpeg-turbo)',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-32498'],
    },
    {
      cve_id: 'CVE-2024-50608',
      title: 'Heap Buffer Overflow in JPEG Encoder',
      description: 'libjpeg-turbo before 3.1.0 has a heap buffer overflow in tjCompress2 when compressing images with specific color-space conversions.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'libjpeg-turbo',
      affected_version: '< 3.1.0',
      fixed_version: '3.1.0',
      remediation: 'Upgrade libjpeg-turbo to 3.1.0 or newer.',
      patch_guidance: 'Upgrade and rebuild image processing tools.',
      ai_fix: '# Build from source if package is outdated:\nwget https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/3.1.0/libjpeg-turbo-3.1.0.tar.gz\ntar xzf libjpeg-turbo-3.1.0.tar.gz\ncd libjpeg-turbo-3.1.0 && cmake -B build && cmake --build build && sudo cmake --install build',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-50608'],
    },
  ],

  // ── libxml2 ───────────────────────────────────────────────────────────────
  libxml2: [
    {
      cve_id: 'CVE-2024-40896',
      title: 'XXE in libxml2 SAX Parser',
      description: 'libxml2 before 2.13.2 processes external entities by default in the SAX parser, enabling XXE attacks when parsing untrusted XML.',
      severity: 'critical',
      cvss_score: 9.1,
      affected_component: 'libxml2',
      affected_version: '< 2.13.2',
      fixed_version: '2.13.2',
      remediation: 'Upgrade libxml2 to 2.13.2+. Disable external entities in parser options.',
      patch_guidance: 'Set XML_PARSE_NOENT and XML_PARSE_DTDLOAD flags off.',
      ai_fix: '// Disable XXE in libxml2:\nxmlParserCtxtPtr ctxt = xmlNewParserCtxt();\nxmlCtxtSetOptions(ctxt,\n    XML_PARSE_NOENT |\n    XML_PARSE_DTDLOAD |\n    XML_PARSE_NONET\n);\n// Or use xmlCtxtReadFile with safe options',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-40896'],
    },
    {
      cve_id: 'CVE-2025-24928',
      title: 'Stack Buffer Overflow in xmlSnprintfElements',
      description: 'libxml2 before 2.13.5 has a stack-based buffer overflow in xmlSnprintfElements via deeply nested element validation errors.',
      severity: 'high',
      cvss_score: 7.8,
      affected_component: 'libxml2',
      affected_version: '< 2.13.5',
      fixed_version: '2.13.5',
      remediation: 'Upgrade libxml2 to 2.13.5 or later.',
      patch_guidance: 'Update system package or bundled copy.',
      ai_fix: '# Upgrade:\nsudo apt-get install libxml2=2.13.5 libxml2-dev=2.13.5',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-24928'],
    },
    {
      cve_id: 'CVE-2024-25062',
      title: 'Use-After-Free in xmlValidatePopElement',
      description: 'libxml2 before 2.12.5 has a use-after-free in xmlValidatePopElement when validating documents with complex content models.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'libxml2',
      affected_version: '< 2.12.5',
      fixed_version: '2.12.5',
      remediation: 'Upgrade libxml2.',
      patch_guidance: 'Update all copies of libxml2 including bundled ones in Python, PHP, etc.',
      ai_fix: '# Update all libxml2 instances:\nsudo apt-get update && sudo apt-get install -y libxml2 libxml2-dev python3-lxml',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-25062'],
    },
  ],

  // ── SQLite ────────────────────────────────────────────────────────────────
  sqlite: [
    {
      cve_id: 'CVE-2024-0232',
      title: 'Use-After-Free in SQLite jsonEachConnect',
      description: 'SQLite before 3.45.1 has a use-after-free in the JSON extension when the json_each virtual table is used with malformed JSON.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'SQLite',
      affected_version: '< 3.45.1',
      fixed_version: '3.45.1',
      remediation: 'Update SQLite to 3.45.1 or later.',
      patch_guidance: 'Update system SQLite and all copies bundled in applications.',
      ai_fix: '// Validate JSON before passing to json_each:\nif (sqlite3_value_type(argv[0]) != SQLITE_TEXT) {\n    sqlite3_result_error(ctx, "Expected JSON text", -1);\n    return;\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-0232'],
    },
    {
      cve_id: 'CVE-2025-29087',
      title: 'Integer Overflow in SQLite concat_ws',
      description: 'SQLite before 3.49.0 has an integer overflow in the concat_ws function that can lead to heap corruption when concatenating very large strings.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'SQLite',
      affected_version: '< 3.49.0',
      fixed_version: '3.49.0',
      remediation: 'Upgrade SQLite to 3.49.0 or later.',
      patch_guidance: 'Upgrade and set SQLITE_MAX_LENGTH to limit string sizes.',
      ai_fix: '// Set safety limits:\nsqlite3_limit(db, SQLITE_LIMIT_LENGTH, 100000000); // 100MB max string\nsqlite3_limit(db, SQLITE_LIMIT_SQL_LENGTH, 1000000);  // 1MB max SQL',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-29087'],
    },
  ],

  // ── libcurl ───────────────────────────────────────────────────────────────
  curl: [
    {
      cve_id: 'CVE-2024-7264',
      title: 'ASN.1 Parsing OOB Read in curl',
      description: 'curl before 8.9.1 has an out-of-bounds read when parsing ASN.1 fields in TLS certificates, crashing the client.',
      severity: 'medium',
      cvss_score: 6.5,
      affected_component: 'libcurl',
      affected_version: '< 8.9.1',
      fixed_version: '8.9.1',
      remediation: 'Update curl/libcurl to 8.9.1+.',
      patch_guidance: 'apt-get install curl libcurl4-openssl-dev',
      ai_fix: '# Upgrade curl:\nsudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev\ncurl --version',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-7264'],
    },
    {
      cve_id: 'CVE-2025-0167',
      title: 'Credential Leak via Netrc on Redirect',
      description: 'curl before 8.12.1 leaks .netrc credentials to redirected hosts when following HTTP redirects, exposing authentication tokens.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'libcurl',
      affected_version: '< 8.12.1',
      fixed_version: '8.12.1',
      remediation: 'Update curl to 8.12.1 or later.',
      patch_guidance: 'Upgrade and avoid using .netrc with redirect-following requests.',
      ai_fix: '// In code using libcurl, disable netrc on redirects:\ncurl_easy_setopt(curl, CURLOPT_NETRC, CURL_NETRC_IGNORED);\ncurl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 0L); // Handle redirects manually',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-0167'],
    },
    {
      cve_id: 'CVE-2024-8096',
      title: 'OCSP Verification Bypass in curl',
      description: 'curl before 8.9.0 does not correctly verify OCSP stapling responses, allowing expired or revoked certificates to be accepted.',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'libcurl',
      affected_version: '< 8.9.0',
      fixed_version: '8.9.0',
      remediation: 'Upgrade curl to 8.9.0 or later.',
      patch_guidance: 'Upgrade and enable strict certificate checking.',
      ai_fix: '// Enable strict SSL verification:\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYSTATUS, 1L);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-8096'],
    },
  ],

  // ── glibc ─────────────────────────────────────────────────────────────────
  glibc: [
    {
      cve_id: 'CVE-2024-2961',
      title: 'Buffer Overflow in iconv() ISO-2022-CN-EXT',
      description: 'glibc before 2.40 has a buffer overflow in iconv() when converting to the ISO-2022-CN-EXT character set, enabling remote code execution.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'glibc',
      affected_version: '< 2.40',
      fixed_version: '2.40',
      remediation: 'Update glibc to 2.40 or apply vendor patches. Requires reboot.',
      patch_guidance: 'apt-get upgrade libc6. Schedule system reboot.',
      ai_fix: '# Upgrade glibc:\nsudo apt-get update && sudo apt-get install -y libc6\n# Verify:\nldd --version\n# Reboot required:\nsudo reboot',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-2961'],
    },
    {
      cve_id: 'CVE-2025-0395',
      title: 'Stack Buffer Overflow in getaddrinfo()',
      description: 'glibc before 2.41 has a stack buffer overflow in getaddrinfo when processing crafted DNS TXT records during host resolution.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'glibc',
      affected_version: '< 2.41',
      fixed_version: '2.41',
      remediation: 'Upgrade glibc. Restrict untrusted DNS resolution.',
      patch_guidance: 'Apply vendor security patch immediately.',
      ai_fix: '# Apply security patch:\nsudo apt-get update && sudo apt-get install -y libc6\nsudo reboot',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-0395'],
    },
  ],

  // ── BusyBox (firmware) ────────────────────────────────────────────────────
  busybox: [
    {
      cve_id: 'CVE-2023-42363',
      title: 'Use-After-Free in BusyBox awk',
      description: 'BusyBox before 1.36.2 has a use-after-free in the awk applet when processing certain scripts, leading to denial of service or code execution on embedded devices.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'BusyBox',
      affected_version: '< 1.36.2',
      fixed_version: '1.36.2',
      remediation: 'Update BusyBox in firmware builds to 1.36.2+.',
      patch_guidance: 'Rebuild firmware image with patched BusyBox.',
      ai_fix: '# In firmware build system (e.g., Buildroot):\n# Update BR2_BUSYBOX_VERSION to 1.36.2\n# Rebuild:\nmake busybox-rebuild all',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-42363'],
    },
    {
      cve_id: 'CVE-2023-42364',
      title: 'Use-After-Free in BusyBox awk evaluate()',
      description: 'BusyBox before 1.36.2 has another use-after-free in the awk evaluate() function.',
      severity: 'medium',
      cvss_score: 5.5,
      affected_component: 'BusyBox',
      affected_version: '< 1.36.2',
      fixed_version: '1.36.2',
      remediation: 'Update BusyBox to 1.36.2 or later.',
      patch_guidance: 'Patch as part of firmware rebuild cycle.',
      ai_fix: '# Update BusyBox in Yocto/Buildroot:\nBUSYBOX_VERSION = "1.36.2"\n# Rebuild firmware',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-42364'],
    },
  ],

  // ── U-Boot (firmware) ─────────────────────────────────────────────────────
  uboot: [
    {
      cve_id: 'CVE-2024-57256',
      title: 'Heap Overflow in U-Boot squashfs Driver',
      description: 'U-Boot before 2025.01 has a heap buffer overflow in the squashfs filesystem driver that can be exploited by a crafted squashfs image to achieve code execution during boot.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'U-Boot',
      affected_version: '< 2025.01',
      fixed_version: '2025.01',
      remediation: 'Update U-Boot to 2025.01. Enable Secure Boot chain.',
      patch_guidance: 'Flash updated bootloader to device. Verify with checksum.',
      ai_fix: '# Build and flash updated U-Boot:\ngit clone https://github.com/u-boot/u-boot\ncd u-boot && git checkout v2025.01\nmake <board>_defconfig\nmake -j$(nproc)\n# Flash to device via JTAG/serial',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-57256'],
    },
    {
      cve_id: 'CVE-2024-57254',
      title: 'Heap Overflow in U-Boot ext4 Driver',
      description: 'U-Boot before 2025.01 has a heap overflow in the ext4 filesystem driver via crafted ext4 superblock metadata.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'U-Boot',
      affected_version: '< 2025.01',
      fixed_version: '2025.01',
      remediation: 'Update U-Boot bootloader firmware.',
      patch_guidance: 'Rebuild and flash updated U-Boot.',
      ai_fix: '# Validate filesystem images before flashing:\ne2fsck -n filesystem.img\n# Update U-Boot to 2025.01+',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-57254'],
    },
  ],

  // ── FreeRTOS (firmware) ───────────────────────────────────────────────────
  freertos: [
    {
      cve_id: 'CVE-2024-28115',
      title: 'Buffer Overflow in FreeRTOS-Plus-TCP DNS Parser',
      description: 'FreeRTOS-Plus-TCP before 4.1.0 has a buffer overflow in the DNS response parser, allowing remote code execution on IoT devices via malicious DNS responses.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'FreeRTOS-Plus-TCP',
      affected_version: '< 4.1.0',
      fixed_version: '4.1.0',
      remediation: 'Update FreeRTOS-Plus-TCP to 4.1.0+. Reflash device firmware.',
      patch_guidance: 'Update FreeRTOS kernel and TCP stack in firmware project.',
      ai_fix: '// Limit DNS response size:\n#define ipconfigDNS_CACHE_NAME_LENGTH  64\n#define ipconfigDNS_REQUEST_MAX_SIZE   512\n// Update FreeRTOS-Plus-TCP submodule to v4.1.0',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-28115'],
    },
    {
      cve_id: 'CVE-2024-28116',
      title: 'Integer Wrap in FreeRTOS TCP Window Scaling',
      description: 'FreeRTOS-Plus-TCP before 4.1.0 has an integer wrap in TCP window size calculation that can corrupt memory.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'FreeRTOS-Plus-TCP',
      affected_version: '< 4.1.0',
      fixed_version: '4.1.0',
      remediation: 'Upgrade FreeRTOS-Plus-TCP stack.',
      patch_guidance: 'Update and rebuild firmware.',
      ai_fix: '// Disable TCP window scaling if not needed:\n#define ipconfigUSE_TCP_WIN  0\n// Or update to FreeRTOS-Plus-TCP v4.1.0+',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-28116'],
    },
  ],

  // ── Alpine (container) ────────────────────────────────────────────────────
  alpine: [
    {
      cve_id: 'CVE-2024-47076',
      title: 'apk-tools Archive Extraction Traversal',
      description: 'Alpine apk-tools before 2.14.4 has a directory traversal during package extraction, allowing a malicious .apk to overwrite files outside the target directory.',
      severity: 'high',
      cvss_score: 8.6,
      affected_component: 'Alpine apk-tools',
      affected_version: '< 2.14.4',
      fixed_version: '2.14.4',
      remediation: 'Update Alpine base image to 3.19.1+ or update apk-tools.',
      patch_guidance: 'FROM alpine:3.19.1 in your Dockerfile.',
      ai_fix: '# Update Dockerfile base image:\nFROM alpine:3.19.1\nRUN apk update && apk upgrade',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47076'],
    },
    {
      cve_id: 'CVE-2024-51744',
      title: 'musl libc DNS Buffer Over-read',
      description: 'musl libc before 1.2.5 (used in Alpine) has a buffer over-read in the DNS resolver when processing SRV records, which can leak memory contents.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'musl libc (Alpine)',
      affected_version: '< 1.2.5',
      fixed_version: '1.2.5',
      remediation: 'Update Alpine image to 3.20+ which ships musl 1.2.5.',
      patch_guidance: 'Update base image and rebuild container.',
      ai_fix: '# Use latest Alpine:\nFROM alpine:3.20\nRUN apk update && apk upgrade --no-cache',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-51744'],
    },
  ],

  // ── Debian (container) ────────────────────────────────────────────────────
  debian: [
    {
      cve_id: 'CVE-2024-38428',
      title: 'URL Parsing Vuln in wget on Debian',
      description: 'wget bundled in Debian before bookworm-20241201 has a URL parsing issue allowing username/password injection into different hosts via semicolons.',
      severity: 'medium',
      cvss_score: 6.5,
      affected_component: 'Debian wget',
      affected_version: '< bookworm-20241201',
      fixed_version: 'bookworm-20241201',
      remediation: 'Update Debian base image. Run apt-get update && apt-get upgrade.',
      patch_guidance: 'Rebuild container from latest Debian tag.',
      ai_fix: '# Dockerfile:\nFROM debian:bookworm-20241201-slim\nRUN apt-get update && apt-get upgrade -y && apt-get clean',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-38428'],
    },
  ],

  // ── nginx ─────────────────────────────────────────────────────────────────
  nginx: [
    {
      cve_id: 'CVE-2024-7347',
      title: 'mp4 Module Buffer Over-Read in nginx',
      description: 'nginx before 1.27.1 has an out-of-bounds read in the mp4 module when processing malformed mp4 files, crashing worker processes.',
      severity: 'medium',
      cvss_score: 5.7,
      affected_component: 'nginx',
      affected_version: '< 1.27.1',
      fixed_version: '1.27.1',
      remediation: 'Upgrade nginx to 1.27.1 or disable mp4 module if unused.',
      patch_guidance: 'apt-get install nginx=1.27.1 or rebuild from source.',
      ai_fix: '# Disable mp4 module if not needed, or upgrade:\nsudo apt-get install nginx=1.27.1-1\nsudo nginx -t && sudo systemctl reload nginx',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-7347'],
    },
    {
      cve_id: 'CVE-2025-23419',
      title: 'TLS Session Resumption Host Bypass in nginx',
      description: 'nginx before 1.27.4 allows bypassing server_name restrictions via TLS session resumption tickets from a different virtual host.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'nginx',
      affected_version: '< 1.27.4',
      fixed_version: '1.27.4',
      remediation: 'Upgrade nginx. Set unique ssl_session_ticket_key per server block.',
      patch_guidance: 'Upgrade and configure separate ticket keys per vhost.',
      ai_fix: '# Per-vhost session ticket keys:\nserver {\n    listen 443 ssl;\n    server_name example.com;\n    ssl_session_ticket_key /etc/nginx/keys/example.com.key;\n    ssl_session_tickets on;\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-23419'],
    },
  ],

  // ── Redis ─────────────────────────────────────────────────────────────────
  redis: [
    {
      cve_id: 'CVE-2024-31449',
      title: 'Lua Script Integer Overflow in Redis',
      description: 'Redis before 7.2.6 has an integer overflow when executing Lua scripts that use the cjson library to encode very large numbers.',
      severity: 'high',
      cvss_score: 7.0,
      affected_component: 'Redis',
      affected_version: '< 7.2.6',
      fixed_version: '7.2.6',
      remediation: 'Update Redis to 7.2.6+ or disable Lua scripting if not needed.',
      patch_guidance: 'Upgrade Redis server and restart.',
      ai_fix: '# Disable Lua scripting if not used:\nrename-command EVAL ""\nrename-command EVALSHA ""\n# Or upgrade Redis:\nsudo apt-get install redis-server=7.2.6',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-31449'],
    },
    {
      cve_id: 'CVE-2024-31228',
      title: 'Denial of Service via Pattern Matching in Redis',
      description: 'Redis before 7.2.6 can be crashed via crafted KEYS or SCAN patterns with complex glob expressions.',
      severity: 'medium',
      cvss_score: 5.5,
      affected_component: 'Redis',
      affected_version: '< 7.2.6',
      fixed_version: '7.2.6',
      remediation: 'Upgrade Redis. Avoid exposing KEYS command.',
      patch_guidance: 'Rename KEYS command and upgrade.',
      ai_fix: '# Disable KEYS command:\nrename-command KEYS ""\n# Use SCAN with count limit instead:\nSCAN 0 MATCH "prefix:*" COUNT 100',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-31228'],
    },
  ],

  // ── libssh / OpenSSH ──────────────────────────────────────────────────────
  libssh: [
    {
      cve_id: 'CVE-2024-6387',
      title: 'Remote Code Execution in OpenSSH (regreSSHion)',
      description: 'OpenSSH before 9.8p1 has a signal handler race condition allowing unauthenticated remote code execution as root on glibc-based Linux systems.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'OpenSSH',
      affected_version: '< 9.8p1',
      fixed_version: '9.8p1',
      remediation: 'Immediately update OpenSSH to 9.8p1. Set LoginGraceTime to 0 as temporary mitigation.',
      patch_guidance: 'Emergency patch. Restart sshd after upgrade.',
      ai_fix: '# Emergency mitigation:\necho "LoginGraceTime 0" >> /etc/ssh/sshd_config\nsudo systemctl restart sshd\n\n# Then upgrade:\nsudo apt-get update && sudo apt-get install -y openssh-server\nsshd -V',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-6387'],
    },
    {
      cve_id: 'CVE-2025-26465',
      title: 'MitM Host Verification Bypass in OpenSSH',
      description: 'OpenSSH before 9.9p2 allows a machine-in-the-middle attacker to bypass host key verification when VerifyHostKeyDNS is enabled.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'OpenSSH',
      affected_version: '< 9.9p2',
      fixed_version: '9.9p2',
      remediation: 'Upgrade OpenSSH. Set VerifyHostKeyDNS=no unless DNSSEC is guaranteed.',
      patch_guidance: 'Disable VerifyHostKeyDNS as mitigation, then upgrade.',
      ai_fix: '# Mitigate and upgrade:\necho "VerifyHostKeyDNS no" >> /etc/ssh/ssh_config\nsudo apt-get update && sudo apt-get install -y openssh-client',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-26465'],
    },
  ],

  // ── FFmpeg ────────────────────────────────────────────────────────────────
  ffmpeg: [
    {
      cve_id: 'CVE-2024-31578',
      title: 'Heap Buffer Overflow in FFmpeg WTVDECRYPT',
      description: 'FFmpeg before 7.0 has a heap buffer overflow in the WTV demuxer that can be triggered by a crafted media file.',
      severity: 'high',
      cvss_score: 7.8,
      affected_component: 'FFmpeg',
      affected_version: '< 7.0',
      fixed_version: '7.0',
      remediation: 'Update FFmpeg to 7.0 or later.',
      patch_guidance: 'Rebuild or install updated FFmpeg binaries.',
      ai_fix: '# Update FFmpeg:\nsudo apt-get install ffmpeg\n# Or build from source:\ngit clone https://git.ffmpeg.org/ffmpeg.git\ncd ffmpeg && git checkout n7.0\n./configure && make -j$(nproc) && sudo make install',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-31578'],
    },
    {
      cve_id: 'CVE-2024-35367',
      title: 'Integer Overflow in FFmpeg AAC Decoder',
      description: 'FFmpeg before 7.0 has an integer overflow in the AAC decoder when processing gain control data, leading to heap corruption.',
      severity: 'high',
      cvss_score: 7.8,
      affected_component: 'FFmpeg',
      affected_version: '< 7.0',
      fixed_version: '7.0',
      remediation: 'Update FFmpeg to 7.0+.',
      patch_guidance: 'Rebuild all applications linking against FFmpeg/libav.',
      ai_fix: '# Update FFmpeg:\nsudo apt-get update && sudo apt-get install -y ffmpeg libavcodec-dev',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-35367'],
    },
  ],

  // ── GRUB (firmware) ───────────────────────────────────────────────────────
  grub: [
    {
      cve_id: 'CVE-2024-45776',
      title: 'Heap Overflow in GRUB2 Config Parser',
      description: 'GRUB2 before 2.12-3 has a heap overflow when parsing a crafted grub.cfg with extremely long variable values, allowing arbitrary code execution at boot.',
      severity: 'critical',
      cvss_score: 9.1,
      affected_component: 'GRUB2',
      affected_version: '< 2.12-3',
      fixed_version: '2.12-3',
      remediation: 'Update GRUB and regenerate boot config.',
      patch_guidance: 'sudo apt-get install grub2 && sudo update-grub. Re-sign if Secure Boot is active.',
      ai_fix: '# Update GRUB:\nsudo apt-get update && sudo apt-get install -y grub2-common grub-efi-amd64-signed\nsudo update-grub\n# If Secure Boot: update shim and re-enroll keys',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-45776'],
    },
  ],

  // ── libwebp ───────────────────────────────────────────────────────────────
  libwebp: [
    {
      cve_id: 'CVE-2023-4863',
      title: 'Critical Heap Overflow in libwebp VP8L Decoder',
      description: 'libwebp before 1.3.2 has a heap buffer overflow in the VP8L lossless decoder via crafted WebP images. Actively exploited in the wild by commercial spyware.',
      severity: 'critical',
      cvss_score: 10.0,
      affected_component: 'libwebp',
      affected_version: '< 1.3.2',
      fixed_version: '1.3.2',
      remediation: 'Immediately update libwebp, browsers, and all image-processing software.',
      patch_guidance: 'Emergency patch. Update every application that processes WebP images.',
      ai_fix: '# Emergency update:\nsudo apt-get update && sudo apt-get install -y libwebp-dev\n# Verify:\npkg-config --modversion libwebp\n# Rebuild apps:\nmake clean && make',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-4863'],
    },
    {
      cve_id: 'CVE-2024-12801',
      title: 'Out-of-bounds Write in libwebp Encoder',
      description: 'libwebp before 1.5.0 has an OOB write in the lossy encoder when specific quality / resize settings are combined.',
      severity: 'high',
      cvss_score: 7.8,
      affected_component: 'libwebp',
      affected_version: '< 1.5.0',
      fixed_version: '1.5.0',
      remediation: 'Upgrade libwebp to 1.5.0 or later.',
      patch_guidance: 'Upgrade system library and rebuild dependent apps.',
      ai_fix: '# Upgrade libwebp:\nsudo apt-get install libwebp-dev=1.5.0',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-12801'],
    },
  ],

  // ── protobuf ──────────────────────────────────────────────────────────────
  protobuf: [
    {
      cve_id: 'CVE-2024-7254',
      title: 'Stack Overflow in Protocol Buffers Java',
      description: 'protobuf-java before 4.27.5 can be crashed via deeply nested messages causing stack overflow during deserialization.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'protobuf',
      affected_version: '< 4.27.5',
      fixed_version: '4.27.5',
      remediation: 'Upgrade protobuf library. Set recursion limits.',
      patch_guidance: 'Upgrade and configure CodedInputStream.setRecursionLimit().',
      ai_fix: '// Set recursion limit for protobuf parsing:\nCodedInputStream input = CodedInputStream.newInstance(data);\ninput.setRecursionLimit(50); // Default is 100\nMyMessage msg = MyMessage.parseFrom(input);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-7254'],
    },
  ],
};
