// Mock CVE Database with 100+ realistic vulnerability entries
// Organized by technology stack / ecosystem

export const CVE_DATABASE = {
  javascript: [
    {
      cve_id: 'CVE-2024-21538',
      title: 'Regular Expression Denial of Service in cross-spawn',
      description: 'Versions of cross-spawn before 7.0.5 are vulnerable to Regular Expression Denial of Service (ReDoS) due to improper input validation in the parsing logic for shell commands.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'cross-spawn',
      affected_version: '< 7.0.5',
      fixed_version: '7.0.5',
      remediation: 'Update cross-spawn to version 7.0.5 or later. Run: npm update cross-spawn',
      patch_guidance: 'Apply patch by upgrading the package. If direct upgrade is not possible, use overrides in package.json to force the patched version.',
      ai_fix: '// In package.json, add:\n"overrides": {\n  "cross-spawn": "^7.0.5"\n}\n// Then run: npm install',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-21538']
    },
    {
      cve_id: 'CVE-2024-48930',
      title: 'Prototype Pollution in body-parser',
      description: 'body-parser before 1.20.3 is vulnerable to prototype pollution when parsing JSON payloads with __proto__ keys, allowing attackers to inject properties into Object.prototype.',
      severity: 'critical',
      cvss_score: 9.1,
      affected_component: 'body-parser',
      affected_version: '< 1.20.3',
      fixed_version: '1.20.3',
      remediation: 'Update body-parser to version 1.20.3 or later.',
      patch_guidance: 'Upgrade body-parser immediately. As a temporary workaround, add middleware to strip __proto__ keys from request bodies.',
      ai_fix: '// Temporary mitigation middleware:\napp.use((req, res, next) => {\n  if (req.body) {\n    const sanitize = (obj) => {\n      delete obj.__proto__;\n      delete obj.constructor;\n      Object.values(obj).forEach(v => {\n        if (v && typeof v === "object") sanitize(v);\n      });\n    };\n    sanitize(req.body);\n  }\n  next();\n});',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-48930']
    },
    {
      cve_id: 'CVE-2024-4067',
      title: 'Path Traversal in micromatch',
      description: 'Micromatch before 4.0.6 has a path traversal vulnerability in the braces expansion that can lead to unauthorized file access when processing user-supplied glob patterns.',
      severity: 'high',
      cvss_score: 7.8,
      affected_component: 'micromatch',
      affected_version: '< 4.0.6',
      fixed_version: '4.0.6',
      remediation: 'Update micromatch to version 4.0.6 or later.',
      patch_guidance: 'Upgrade the package and ensure glob patterns from user input are sanitized before processing.',
      ai_fix: '// Sanitize glob patterns before passing to micromatch:\nfunction sanitizeGlob(pattern) {\n  return pattern.replace(/\\.\\./g, "").replace(/\\0/g, "");\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-4067']
    },
    {
      cve_id: 'CVE-2024-29041',
      title: 'Open Redirect in Express.js',
      description: 'Express.js before 4.19.2 does not properly validate the redirect URL in res.redirect(), allowing open redirect attacks via URLs with backslashes.',
      severity: 'medium',
      cvss_score: 6.1,
      affected_component: 'express',
      affected_version: '< 4.19.2',
      fixed_version: '4.19.2',
      remediation: 'Update Express.js to version 4.19.2 or later.',
      patch_guidance: 'Upgrade Express. Validate redirect URLs against an allowlist as defense in depth.',
      ai_fix: '// Validate redirect URLs:\nfunction safeRedirect(res, url) {\n  const allowed = ["/dashboard", "/login", "/"];\n  if (allowed.includes(url)) {\n    return res.redirect(url);\n  }\n  return res.redirect("/");\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-29041']
    },
    {
      cve_id: 'CVE-2025-27789',
      title: 'Server-Side Request Forgery in axios',
      description: 'Axios versions before 1.8.2 are vulnerable to SSRF when following redirects. An attacker-controlled redirect can cause the server to make requests to internal services.',
      severity: 'high',
      cvss_score: 8.2,
      affected_component: 'axios',
      affected_version: '< 1.8.2',
      fixed_version: '1.8.2',
      remediation: 'Update axios to version 1.8.2 or later.',
      patch_guidance: 'Upgrade axios. Configure maxRedirects and validate redirect targets.',
      ai_fix: '// Configure axios with SSRF protections:\nconst axios = require("axios");\nconst instance = axios.create({\n  maxRedirects: 5,\n  beforeRedirect: (options) => {\n    const url = new URL(options.href);\n    if (url.hostname === "localhost" || url.hostname.startsWith("127.")) {\n      throw new Error("SSRF attempt blocked");\n    }\n  }\n});',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2025-27789']
    },
    {
      cve_id: 'CVE-2024-47764',
      title: 'Cookie Injection in cookie Package',
      description: 'The cookie package before 0.7.0 does not properly validate cookie names and values, allowing attackers to inject additional cookies or modify existing ones.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'cookie',
      affected_version: '< 0.7.0',
      fixed_version: '0.7.0',
      remediation: 'Update cookie to version 0.7.0 or later.',
      patch_guidance: 'Upgrade the package. Validate cookie names and values using a strict pattern.',
      ai_fix: '// Validate cookie values:\nfunction isValidCookieValue(value) {\n  return /^[\\u0021\\u0023-\\u002B\\u002D-\\u003A\\u003C-\\u005B\\u005D-\\u007E]*$/.test(value);\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47764']
    },
    {
      cve_id: 'CVE-2024-37890',
      title: 'Denial of Service in ws WebSocket Library',
      description: 'The ws package before 8.17.1 allows a denial of service when handling specially crafted HTTP headers during the WebSocket upgrade, leading to excessive memory usage.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'ws',
      affected_version: '< 8.17.1',
      fixed_version: '8.17.1',
      remediation: 'Update ws to version 8.17.1 or later.',
      patch_guidance: 'Upgrade ws. Set maxPayload limit on the WebSocket server.',
      ai_fix: '// Set limits on WebSocket server:\nconst WebSocket = require("ws");\nconst wss = new WebSocket.Server({\n  port: 8080,\n  maxPayload: 1024 * 1024, // 1MB limit\n  perMessageDeflate: false\n});',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-37890']
    },
    {
      cve_id: 'CVE-2024-39338',
      title: 'Path Traversal in send Package',
      description: 'send package before 0.19.0 allows path traversal attacks via specially crafted URLs with encoded dot-dot sequences, potentially exposing files outside the served directory.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'send',
      affected_version: '< 0.19.0',
      fixed_version: '0.19.0',
      remediation: 'Update send to version 0.19.0 or later.',
      patch_guidance: 'Upgrade send package. This is often a transitive dependency of express.static().',
      ai_fix: '// Ensure express is updated which includes send:\n// In package.json:\n"dependencies": {\n  "express": "^4.20.0"\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-39338']
    },
    {
      cve_id: 'CVE-2024-33883',
      title: 'Prototype Pollution in ejs Template Engine',
      description: 'EJS before 3.1.10 is vulnerable to prototype pollution via the settings option. An attacker can inject arbitrary properties into Object.prototype via template options.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'ejs',
      affected_version: '< 3.1.10',
      fixed_version: '3.1.10',
      remediation: 'Update ejs to version 3.1.10 or later.',
      patch_guidance: 'Upgrade ejs. Never pass user-controlled data as template options. Use Object.create(null) for template data.',
      ai_fix: '// Secure EJS rendering:\nconst ejs = require("ejs");\n\n// Use a null-prototype object for data\nconst data = Object.create(null);\ndata.title = userInput;\n\nconst html = ejs.render(template, data, {\n  async: false,\n  destructuredLocals: []\n});',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-33883']
    },
    {
      cve_id: 'CVE-2024-28176',
      title: 'Resource Exhaustion in jose JWT Library',
      description: 'jose before 4.15.5 is vulnerable to resource exhaustion when decrypting JWE tokens with large compressed payloads (zip bomb attack).',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'jose',
      affected_version: '< 4.15.5',
      fixed_version: '4.15.5',
      remediation: 'Update jose to version 4.15.5 or later.',
      patch_guidance: 'Upgrade jose. Set a contentEncryptionAlgorithms allowlist when decrypting.',
      ai_fix: '// Configure jose with safe defaults:\nimport { jwtDecrypt } from "jose";\n\nconst result = await jwtDecrypt(token, key, {\n  contentEncryptionAlgorithms: ["A256GCM"],\n  maxPBES2Count: 10000\n});',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-28176']
    },
  ],

  python: [
    {
      cve_id: 'CVE-2024-53981',
      title: 'SQL Injection in SQLAlchemy ORM',
      description: 'SQLAlchemy before 2.0.36 allows SQL injection through the order_by() clause when accepting raw user input as column names without proper sanitization.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'sqlalchemy',
      affected_version: '< 2.0.36',
      fixed_version: '2.0.36',
      remediation: 'Update SQLAlchemy to 2.0.36+. Always use column objects, never raw strings from user input in order_by().',
      patch_guidance: 'pip install --upgrade sqlalchemy>=2.0.36',
      ai_fix: '# Unsafe:\nquery.order_by(user_input)\n\n# Safe:\nfrom sqlalchemy import asc, desc\nALLOWED_COLUMNS = {"name": Model.name, "date": Model.created_at}\ncol = ALLOWED_COLUMNS.get(user_input)\nif col:\n    query = query.order_by(asc(col))',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-53981']
    },
    {
      cve_id: 'CVE-2024-47874',
      title: 'Remote Code Execution in Starlette',
      description: 'Starlette before 0.40.0 allows remote code execution through multipart form data parsing due to unsafe use of tempfile in combination with user-controlled filenames.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'starlette',
      affected_version: '< 0.40.0',
      fixed_version: '0.40.0',
      remediation: 'Update Starlette to 0.40.0 or later.',
      patch_guidance: 'pip install --upgrade starlette>=0.40.0',
      ai_fix: '# Sanitize uploaded filenames:\nimport os\nimport re\n\ndef sanitize_filename(filename):\n    # Remove path separators and null bytes\n    filename = os.path.basename(filename)\n    filename = re.sub(r"[^\\w\\s.-]", "", filename)\n    return filename[:255]  # Limit length',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47874']
    },
    {
      cve_id: 'CVE-2024-49768',
      title: 'HTTP Request Smuggling in Waitress',
      description: 'Waitress WSGI server before 3.0.1 is vulnerable to HTTP request smuggling due to improper handling of Transfer-Encoding headers.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'waitress',
      affected_version: '< 3.0.1',
      fixed_version: '3.0.1',
      remediation: 'Update waitress to 3.0.1 or later. Consider switching to gunicorn in production.',
      patch_guidance: 'pip install --upgrade waitress>=3.0.1',
      ai_fix: '# Switch to gunicorn for production:\n# gunicorn app:app --bind 0.0.0.0:8000 --workers 4',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-49768']
    },
    {
      cve_id: 'CVE-2024-6345',
      title: 'Arbitrary Code Execution in setuptools',
      description: 'setuptools before 70.0.0 allows arbitrary code execution via crafted package URLs in the package_data configuration during installation.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'setuptools',
      affected_version: '< 70.0.0',
      fixed_version: '70.0.0',
      remediation: 'Update setuptools to version 70.0.0 or later.',
      patch_guidance: 'pip install --upgrade setuptools>=70.0.0',
      ai_fix: '# Update setuptools:\nimport subprocess\nsubprocess.run(["pip", "install", "--upgrade", "setuptools>=70.0.0"])',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-6345']
    },
    {
      cve_id: 'CVE-2024-35195',
      title: 'Session Credential Leak in Requests',
      description: 'The requests library before 2.32.0 leaks Proxy-Authorization headers to destination servers when redirected from HTTPS to HTTP endpoints.',
      severity: 'medium',
      cvss_score: 5.6,
      affected_component: 'requests',
      affected_version: '< 2.32.0',
      fixed_version: '2.32.0',
      remediation: 'Update requests to 2.32.0 or later.',
      patch_guidance: 'pip install --upgrade requests>=2.32.0',
      ai_fix: '# Safe request with redirect validation:\nimport requests\n\nsession = requests.Session()\nsession.max_redirects = 5\nresponse = session.get(url, allow_redirects=False)\n# Manually follow redirects with validation',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-35195']
    },
    {
      cve_id: 'CVE-2024-3651',
      title: 'Denial of Service in idna Package',
      description: 'The idna package before 3.7 is vulnerable to denial of service through specially crafted internationalized domain names that cause excessive CPU consumption.',
      severity: 'medium',
      cvss_score: 6.5,
      affected_component: 'idna',
      affected_version: '< 3.7',
      fixed_version: '3.7',
      remediation: 'Update idna to version 3.7 or later.',
      patch_guidance: 'pip install --upgrade idna>=3.7',
      ai_fix: '# Validate domain names before processing:\nimport re\ndef validate_domain(domain):\n    if len(domain) > 253:\n        raise ValueError("Domain too long")\n    if not re.match(r"^[a-zA-Z0-9.-]+$", domain):\n        raise ValueError("Invalid domain characters")\n    return domain',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-3651']
    },
    {
      cve_id: 'CVE-2024-22195',
      title: 'Cross-Site Scripting in Jinja2',
      description: 'Jinja2 before 3.1.3 has an XSS vulnerability in the xmlattr filter when rendering user-controlled data as HTML attributes.',
      severity: 'medium',
      cvss_score: 6.1,
      affected_component: 'jinja2',
      affected_version: '< 3.1.3',
      fixed_version: '3.1.3',
      remediation: 'Update Jinja2 to 3.1.3 or later. Enable autoescape globally.',
      patch_guidance: 'pip install --upgrade Jinja2>=3.1.3',
      ai_fix: '# Enable autoescape in Jinja2:\nfrom jinja2 import Environment, select_autoescape\n\nenv = Environment(\n    autoescape=select_autoescape(["html", "xml"])\n)',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-22195']
    },
    {
      cve_id: 'CVE-2024-21503',
      title: 'ReDoS in Django URL Validation',
      description: 'Django before 5.0.3 is vulnerable to Regular Expression Denial of Service in the URLValidator when processing certain crafted URLs.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'django',
      affected_version: '< 5.0.3',
      fixed_version: '5.0.3',
      remediation: 'Update Django to 5.0.3 or later.',
      patch_guidance: 'pip install --upgrade Django>=5.0.3',
      ai_fix: '# Use Django\'s built-in URLValidator with timeout:\nfrom django.core.validators import URLValidator\nvalidator = URLValidator()\ntry:\n    validator(url)\nexcept ValidationError:\n    pass  # Invalid URL',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-21503']
    },
    {
      cve_id: 'CVE-2024-24762',
      title: 'Multipart DoS in python-multipart',
      description: 'python-multipart before 0.0.7 is vulnerable to denial of service via crafted multipart form data with deeply nested boundaries.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'python-multipart',
      affected_version: '< 0.0.7',
      fixed_version: '0.0.7',
      remediation: 'Update python-multipart to 0.0.7 or later.',
      patch_guidance: 'pip install --upgrade python-multipart>=0.0.7',
      ai_fix: '# Limit multipart depth and size:\nfrom starlette.middleware import Middleware\nfrom starlette.middleware.trustedhost import TrustedHostMiddleware\n\n# Set max request size\napp = FastAPI()\n\n@app.middleware("http")\nasync def limit_upload_size(request, call_next):\n    if request.headers.get("content-length"):\n        if int(request.headers["content-length"]) > 10_000_000:\n            return JSONResponse(status_code=413, content={"error": "Too large"})\n    return await call_next(request)',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-24762']
    },
    {
      cve_id: 'CVE-2024-47561',
      title: 'Arbitrary Code Execution in Apache Avro Python',
      description: 'Apache Avro Python SDK before 1.11.4 allows arbitrary code execution when deserializing untrusted Avro schemas due to unsafe use of eval().',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'apache-avro',
      affected_version: '< 1.11.4',
      fixed_version: '1.11.4',
      remediation: 'Update apache-avro to 1.11.4 or later. Never deserialize untrusted schemas.',
      patch_guidance: 'pip install --upgrade apache-avro>=1.11.4',
      ai_fix: '# Validate Avro schemas before parsing:\nimport json\ndef validate_avro_schema(schema_str):\n    schema = json.loads(schema_str)\n    allowed_types = {"null", "boolean", "int", "long", "float", "double", "string", "bytes", "record", "enum", "array", "map", "union", "fixed"}\n    if schema.get("type") not in allowed_types:\n        raise ValueError(f"Invalid schema type: {schema.get(\'type\')}")',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47561']
    },
  ],

  java: [
    {
      cve_id: 'CVE-2024-38816',
      title: 'Path Traversal in Spring Framework',
      description: 'Spring Framework before 6.1.13 allows path traversal when serving static resources via functional web frameworks, enabling access to files outside the intended directory.',
      severity: 'critical',
      cvss_score: 9.1,
      affected_component: 'spring-framework',
      affected_version: '< 6.1.13',
      fixed_version: '6.1.13',
      remediation: 'Update Spring Framework to 6.1.13 or later.',
      patch_guidance: 'Update the spring-webmvc dependency in pom.xml or build.gradle.',
      ai_fix: '<!-- In pom.xml -->\n<dependency>\n    <groupId>org.springframework</groupId>\n    <artifactId>spring-webmvc</artifactId>\n    <version>6.1.13</version>\n</dependency>',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-38816']
    },
    {
      cve_id: 'CVE-2024-38809',
      title: 'DoS via Malformed ETag in Spring Framework',
      description: 'Spring Framework before 6.1.12 is vulnerable to denial of service when processing requests with malformed ETag headers.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'spring-framework',
      affected_version: '< 6.1.12',
      fixed_version: '6.1.12',
      remediation: 'Update Spring Framework to 6.1.12 or later.',
      patch_guidance: 'Update spring-web dependency.',
      ai_fix: '// Add ETag validation filter:\n@Component\npublic class ETagFilter extends OncePerRequestFilter {\n    @Override\n    protected void doFilterInternal(HttpServletRequest request,\n            HttpServletResponse response, FilterChain chain) {\n        String etag = request.getHeader("If-None-Match");\n        if (etag != null && etag.length() > 8192) {\n            response.setStatus(400);\n            return;\n        }\n        chain.doFilter(request, response);\n    }\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-38809']
    },
    {
      cve_id: 'CVE-2024-31573',
      title: 'XXE in Xerces2 XML Parser',
      description: 'Apache Xerces2 Java before 2.12.2-jaxb-1.0.6 allows XML External Entity attacks when parsing untrusted XML with external entity resolution enabled.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'xerces2-j',
      affected_version: '< 2.12.2',
      fixed_version: '2.12.2',
      remediation: 'Update Xerces2 to 2.12.2 or later. Disable external entity processing.',
      patch_guidance: 'Update dependency and disable DTD processing.',
      ai_fix: '// Secure XML parser configuration:\nDocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();\ndbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);\ndbf.setFeature("http://xml.org/sax/features/external-general-entities", false);\ndbf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);\ndbf.setXIncludeAware(false);\ndbf.setExpandEntityReferences(false);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-31573']
    },
    {
      cve_id: 'CVE-2024-22262',
      title: 'Open Redirect in Spring Framework UriComponentsBuilder',
      description: 'Spring Framework UriComponentsBuilder before 6.1.6 incorrectly handles user info in URIs, allowing open redirect attacks.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'spring-web',
      affected_version: '< 6.1.6',
      fixed_version: '6.1.6',
      remediation: 'Update Spring Framework to 6.1.6 or later.',
      patch_guidance: 'Update spring-web dependency in your build configuration.',
      ai_fix: '// Validate redirect URLs:\npublic boolean isValidRedirect(String url) {\n    try {\n        URI uri = new URI(url);\n        return uri.getHost() == null || \n               uri.getHost().endsWith(".yourdomain.com");\n    } catch (URISyntaxException e) {\n        return false;\n    }\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-22262']
    },
    {
      cve_id: 'CVE-2024-52316',
      title: 'Authentication Bypass in Apache Tomcat',
      description: 'Apache Tomcat before 11.0.1 allows authentication bypass when a custom Jakarta Authentication ServerAuthContext returns without setting HTTP status when authentication fails.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'apache-tomcat',
      affected_version: '< 11.0.1',
      fixed_version: '11.0.1',
      remediation: 'Update Apache Tomcat to 11.0.1 or later.',
      patch_guidance: 'Upgrade Tomcat. Ensure custom ServerAuthContext always sets appropriate HTTP status.',
      ai_fix: '// Ensure authentication module sets status:\npublic AuthStatus validateRequest(MessageInfo messageInfo, \n        Subject clientSubject, Subject serviceSubject) {\n    try {\n        // ... authentication logic\n        if (!authenticated) {\n            HttpServletResponse response = \n                (HttpServletResponse) messageInfo.getResponseMessage();\n            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);\n            return AuthStatus.SEND_FAILURE;\n        }\n        return AuthStatus.SUCCESS;\n    } catch (Exception e) {\n        return AuthStatus.SEND_FAILURE;\n    }\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-52316']
    },
    {
      cve_id: 'CVE-2024-12798',
      title: 'Arbitrary Code Execution in Logback',
      description: 'Logback before 1.5.12 allows arbitrary code execution via crafted logback.xml configuration files that use JNDI lookups.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'logback-core',
      affected_version: '< 1.5.12',
      fixed_version: '1.5.12',
      remediation: 'Update Logback to 1.5.12 or later.',
      patch_guidance: 'Update logback-core and logback-classic dependencies.',
      ai_fix: '<!-- In pom.xml -->\n<dependency>\n    <groupId>ch.qos.logback</groupId>\n    <artifactId>logback-classic</artifactId>\n    <version>1.5.12</version>\n</dependency>',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-12798']
    },
    {
      cve_id: 'CVE-2024-22243',
      title: 'SSRF in Spring Framework UriComponentsBuilder',
      description: 'Spring Framework before 6.1.5 allows SSRF attacks through UriComponentsBuilder when constructing URIs from user input.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'spring-web',
      affected_version: '< 6.1.5',
      fixed_version: '6.1.5',
      remediation: 'Update Spring Framework to 6.1.5 or later.',
      patch_guidance: 'Update spring-web. Validate user-supplied URLs before use.',
      ai_fix: '// Validate URLs to prevent SSRF:\npublic boolean isSafeUrl(String url) {\n    try {\n        URI uri = URI.create(url);\n        InetAddress addr = InetAddress.getByName(uri.getHost());\n        return !addr.isLoopbackAddress() && \n               !addr.isSiteLocalAddress() && \n               !addr.isLinkLocalAddress();\n    } catch (Exception e) {\n        return false;\n    }\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-22243']
    },
    {
      cve_id: 'CVE-2024-25710',
      title: 'Denial of Service in Apache Commons Compress',
      description: 'Apache Commons Compress before 1.26.0 is vulnerable to denial of service when processing crafted ZIP files with large uncompressed entries.',
      severity: 'medium',
      cvss_score: 5.5,
      affected_component: 'commons-compress',
      affected_version: '< 1.26.0',
      fixed_version: '1.26.0',
      remediation: 'Update Commons Compress to 1.26.0 or later.',
      patch_guidance: 'Update the commons-compress dependency.',
      ai_fix: '<!-- In pom.xml -->\n<dependency>\n    <groupId>org.apache.commons</groupId>\n    <artifactId>commons-compress</artifactId>\n    <version>1.26.0</version>\n</dependency>',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-25710']
    },
  ],

  go: [
    {
      cve_id: 'CVE-2024-24790',
      title: 'Incorrect IP Address Parsing in Go net Package',
      description: 'Go standard library net package before 1.22.4 incorrectly parses IPv4-mapped IPv6 addresses, potentially allowing bypass of IP-based access controls.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'golang/net',
      affected_version: '< 1.22.4',
      fixed_version: '1.22.4',
      remediation: 'Update Go to version 1.22.4 or later.',
      patch_guidance: 'Update Go toolchain version in go.mod.',
      ai_fix: '// Validate IP addresses properly:\nfunc isAllowedIP(ipStr string) bool {\n    ip := net.ParseIP(ipStr)\n    if ip == nil {\n        return false\n    }\n    // Convert to canonical form\n    if ip4 := ip.To4(); ip4 != nil {\n        ip = ip4\n    }\n    // Check against blocklist\n    return !ip.IsLoopback() && !ip.IsPrivate()\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-24790']
    },
    {
      cve_id: 'CVE-2024-24789',
      title: 'Archive Traversal in Go archive/zip',
      description: 'Go before 1.22.4 has a directory traversal vulnerability in archive/zip that allows extracting files outside the target directory.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'golang/archive',
      affected_version: '< 1.22.4',
      fixed_version: '1.22.4',
      remediation: 'Update Go to version 1.22.4 or later.',
      patch_guidance: 'Update Go version. Add path validation when extracting archives.',
      ai_fix: '// Safe archive extraction:\nfunc safeExtract(f *zip.File, destDir string) error {\n    path := filepath.Join(destDir, f.Name)\n    if !strings.HasPrefix(filepath.Clean(path), filepath.Clean(destDir)+string(os.PathSeparator)) {\n        return fmt.Errorf("illegal file path: %s", f.Name)\n    }\n    // ... proceed with extraction\n    return nil\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-24789']
    },
    {
      cve_id: 'CVE-2024-24791',
      title: 'HTTP/2 Rapid Reset in Go net/http',
      description: 'Go net/http server before 1.22.5 is vulnerable to the HTTP/2 Rapid Reset attack, allowing denial of service through rapid stream creation and cancellation.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'golang/net/http',
      affected_version: '< 1.22.5',
      fixed_version: '1.22.5',
      remediation: 'Update Go to version 1.22.5 or later.',
      patch_guidance: 'Update Go toolchain. Configure HTTP/2 connection limits.',
      ai_fix: '// Configure HTTP/2 limits:\nserver := &http.Server{\n    ReadTimeout:  10 * time.Second,\n    WriteTimeout: 10 * time.Second,\n    IdleTimeout:  30 * time.Second,\n    MaxHeaderBytes: 1 << 20,\n}\n\n// Optionally disable HTTP/2:\nserver.TLSNextProto = make(map[string]func(*http.Server, *tls.Conn, http.Handler))',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-24791']
    },
    {
      cve_id: 'CVE-2024-34156',
      title: 'Stack Exhaustion in Go encoding/gob',
      description: 'Go encoding/gob before 1.23.1 allows stack exhaustion when decoding deeply nested structures, leading to denial of service.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'golang/encoding',
      affected_version: '< 1.23.1',
      fixed_version: '1.23.1',
      remediation: 'Update Go to version 1.23.1 or later.',
      patch_guidance: 'Update Go toolchain. Limit nesting depth for untrusted input.',
      ai_fix: '// Use JSON with depth limiting instead of gob for untrusted input:\nfunc decodeWithLimit(data []byte, maxDepth int) (interface{}, error) {\n    var result interface{}\n    dec := json.NewDecoder(bytes.NewReader(data))\n    dec.DisallowUnknownFields()\n    if err := dec.Decode(&result); err != nil {\n        return nil, err\n    }\n    if getDepth(result) > maxDepth {\n        return nil, fmt.Errorf("exceeded max depth %d", maxDepth)\n    }\n    return result, nil\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-34156']
    },
    {
      cve_id: 'CVE-2024-34155',
      title: 'Stack Exhaustion in Go go/parser',
      description: 'Go go/parser before 1.23.1 allows stack exhaustion when parsing deeply nested Go source files.',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'golang/go/parser',
      affected_version: '< 1.23.1',
      fixed_version: '1.23.1',
      remediation: 'Update Go to version 1.23.1 or later.',
      patch_guidance: 'Update Go toolchain version.',
      ai_fix: '// Set goroutine stack size limit:\n// In production, limit parsed file size:\nfunc safeParse(filename string) (*ast.File, error) {\n    info, _ := os.Stat(filename)\n    if info.Size() > 10*1024*1024 { // 10MB limit\n        return nil, fmt.Errorf("file too large to parse")\n    }\n    return parser.ParseFile(fset, filename, nil, parser.AllErrors)\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-34155']
    },
  ],

  rust: [
    {
      cve_id: 'CVE-2024-32650',
      title: 'Panic in rustls TLS Library',
      description: 'rustls before 0.23.5 panics when processing a ClientHello with an empty cipher suites list, leading to denial of service for TLS servers.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'rustls',
      affected_version: '< 0.23.5',
      fixed_version: '0.23.5',
      remediation: 'Update rustls to 0.23.5 or later.',
      patch_guidance: 'Update Cargo.toml dependency version.',
      ai_fix: '# In Cargo.toml:\n[dependencies]\nrustls = "0.23.5"',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-32650']
    },
    {
      cve_id: 'CVE-2024-12224',
      title: 'Certificate Verification Bypass in rustls',
      description: 'rustls before 0.23.20 may accept server certificates signed by a CA not in the trust store under certain timing conditions.',
      severity: 'critical',
      cvss_score: 9.1,
      affected_component: 'rustls',
      affected_version: '< 0.23.20',
      fixed_version: '0.23.20',
      remediation: 'Update rustls to 0.23.20 or later.',
      patch_guidance: 'Update Cargo.toml and run cargo update.',
      ai_fix: '# In Cargo.toml:\n[dependencies]\nrustls = ">=0.23.20"\n\n# Then run:\n# cargo update -p rustls',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-12224']
    },
    {
      cve_id: 'CVE-2024-47813',
      title: 'Insufficient Validation in wasmtime',
      description: 'wasmtime before 25.0.2 has insufficient validation of WASM modules that can lead to memory corruption when executing malicious modules.',
      severity: 'high',
      cvss_score: 8.6,
      affected_component: 'wasmtime',
      affected_version: '< 25.0.2',
      fixed_version: '25.0.2',
      remediation: 'Update wasmtime to 25.0.2 or later.',
      patch_guidance: 'Update the wasmtime dependency in Cargo.toml.',
      ai_fix: '# In Cargo.toml:\n[dependencies]\nwasmtime = ">=25.0.2"\n\n# Enable additional safety checks:\nlet mut config = Config::new();\nconfig.cranelift_nan_canonicalization(true);\nconfig.guard_before_linear_memory(true);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47813']
    },
  ],

  php: [
    {
      cve_id: 'CVE-2024-8932',
      title: 'Heap Buffer Overflow in PHP ldap_escape',
      description: 'PHP before 8.3.14 has a heap buffer overflow in ldap_escape() when processing specially crafted input strings.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'php',
      affected_version: '< 8.3.14',
      fixed_version: '8.3.14',
      remediation: 'Update PHP to 8.3.14 or later.',
      patch_guidance: 'Update PHP runtime. Validate input before passing to ldap_escape().',
      ai_fix: '<?php\n// Validate input before LDAP operations:\nfunction safeLdapEscape(string $value): string {\n    if (strlen($value) > 1000) {\n        throw new InvalidArgumentException("Input too long");\n    }\n    return ldap_escape($value, "", LDAP_ESCAPE_FILTER);\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-8932']
    },
    {
      cve_id: 'CVE-2024-11236',
      title: 'Integer Overflow in PHP mysqlnd',
      description: 'PHP mysqlnd driver before 8.3.14 has an integer overflow vulnerability when processing large result sets from MySQL servers.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'php-mysqlnd',
      affected_version: '< 8.3.14',
      fixed_version: '8.3.14',
      remediation: 'Update PHP to 8.3.14 or later.',
      patch_guidance: 'Update PHP runtime. Use parameterized queries and limit result sizes.',
      ai_fix: '<?php\n// Limit query results:\n$stmt = $pdo->prepare("SELECT * FROM users LIMIT :limit");\n$stmt->bindValue(":limit", min($requestedLimit, 1000), PDO::PARAM_INT);\n$stmt->execute();',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-11236']
    },
    {
      cve_id: 'CVE-2024-9026',
      title: 'Log Injection in PHP-FPM',
      description: 'PHP-FPM before 8.3.12 allows log injection via specially crafted error messages, enabling log forging and potential log-based attacks.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'php-fpm',
      affected_version: '< 8.3.12',
      fixed_version: '8.3.12',
      remediation: 'Update PHP to 8.3.12 or later.',
      patch_guidance: 'Update PHP-FPM. Sanitize log output.',
      ai_fix: '<?php\n// Sanitize log messages:\nfunction safeLog(string $message): void {\n    $sanitized = str_replace(["\\n", "\\r", "\\t"], " ", $message);\n    $sanitized = preg_replace("/[^\\x20-\\x7E]/", "", $sanitized);\n    error_log($sanitized);\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-9026']
    },
    {
      cve_id: 'CVE-2024-2756',
      title: 'Cookie Bypass in PHP',
      description: 'PHP before 8.3.5 has a vulnerability where __Host- and __Secure- cookie name prefixes are not properly validated, allowing cookie injection attacks.',
      severity: 'medium',
      cvss_score: 6.5,
      affected_component: 'php',
      affected_version: '< 8.3.5',
      fixed_version: '8.3.5',
      remediation: 'Update PHP to 8.3.5 or later.',
      patch_guidance: 'Update PHP runtime.',
      ai_fix: '<?php\n// Secure cookie settings:\nsetcookie("session", $value, [\n    "expires" => time() + 3600,\n    "path" => "/",\n    "domain" => ".yourdomain.com",\n    "secure" => true,\n    "httponly" => true,\n    "samesite" => "Strict"\n]);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-2756']
    },
  ],

  ruby: [
    {
      cve_id: 'CVE-2024-26146',
      title: 'ReDoS in Rack Header Parsing',
      description: 'Rack before 3.0.9.1 is vulnerable to denial of service when parsing crafted Accept headers due to catastrophic backtracking in regular expressions.',
      severity: 'medium',
      cvss_score: 5.3,
      affected_component: 'rack',
      affected_version: '< 3.0.9.1',
      fixed_version: '3.0.9.1',
      remediation: 'Update rack gem to 3.0.9.1 or later.',
      patch_guidance: 'gem update rack',
      ai_fix: '# In Gemfile:\ngem "rack", ">= 3.0.9.1"\n\n# Then run:\n# bundle update rack',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-26146']
    },
    {
      cve_id: 'CVE-2024-26144',
      title: 'Sensitive Data Exposure in Rails Action Controller',
      description: 'Rails before 7.1.3.2 leaks session cookies on redirects to external domains when using the redirect_to helper.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'rails',
      affected_version: '< 7.1.3.2',
      fixed_version: '7.1.3.2',
      remediation: 'Update Rails to 7.1.3.2 or later.',
      patch_guidance: 'gem update rails',
      ai_fix: '# In Gemfile:\ngem "rails", ">= 7.1.3.2"\n\n# Validate redirect targets:\ndef safe_redirect(url)\n  uri = URI.parse(url)\n  if uri.host.nil? || uri.host.end_with?(".yourdomain.com")\n    redirect_to url\n  else\n    redirect_to root_path\n  end\nend',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-26144']
    },
    {
      cve_id: 'CVE-2024-26143',
      title: 'XSS in Rails Action Text',
      description: 'Rails Action Text before 7.1.3.2 is vulnerable to cross-site scripting when rendering rich text content with crafted attachments.',
      severity: 'medium',
      cvss_score: 6.1,
      affected_component: 'actiontext',
      affected_version: '< 7.1.3.2',
      fixed_version: '7.1.3.2',
      remediation: 'Update Rails to 7.1.3.2 or later.',
      patch_guidance: 'gem update rails actiontext',
      ai_fix: '# In Gemfile:\ngem "rails", ">= 7.1.3.2"\n\n# Sanitize rich text output:\n<%= sanitize(post.content.to_s, tags: %w[p br strong em]) %>',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-26143']
    },
  ],

  csharp: [
    {
      cve_id: 'CVE-2024-43484',
      title: 'DoS in .NET System.IO.Packaging',
      description: '.NET before 8.0.10 is vulnerable to denial of service when processing crafted ZIP packages via System.IO.Packaging.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'dotnet-runtime',
      affected_version: '< 8.0.10',
      fixed_version: '8.0.10',
      remediation: 'Update .NET Runtime to 8.0.10 or later.',
      patch_guidance: 'dotnet workload update && dotnet restore',
      ai_fix: '// Validate ZIP entries before extraction:\nusing var archive = ZipFile.OpenRead(path);\nforeach (var entry in archive.Entries)\n{\n    var destPath = Path.GetFullPath(Path.Combine(destDir, entry.FullName));\n    if (!destPath.StartsWith(Path.GetFullPath(destDir)))\n    {\n        throw new InvalidOperationException("Zip slip detected");\n    }\n    if (entry.Length > 100_000_000) // 100MB limit\n    {\n        throw new InvalidOperationException("Entry too large");\n    }\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-43484']
    },
    {
      cve_id: 'CVE-2024-43483',
      title: 'DoS in .NET System.Security.Cryptography',
      description: '.NET before 8.0.10 is vulnerable to denial of service when processing specially crafted X.509 certificates with large CRL distribution point extensions.',
      severity: 'high',
      cvss_score: 7.5,
      affected_component: 'dotnet-runtime',
      affected_version: '< 8.0.10',
      fixed_version: '8.0.10',
      remediation: 'Update .NET Runtime to 8.0.10 or later.',
      patch_guidance: 'Update .NET SDK and runtime.',
      ai_fix: '// Validate certificates with timeout:\nusing var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));\ntry {\n    var chain = new X509Chain();\n    chain.ChainPolicy.VerificationTime = DateTime.UtcNow;\n    chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck; // Skip CRL\n    var result = chain.Build(cert);\n} catch (OperationCanceledException) {\n    // Certificate validation timed out\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-43483']
    },
  ],

  docker: [
    {
      cve_id: 'CVE-2024-41110',
      title: 'AuthZ Plugin Bypass in Docker Engine',
      description: 'Docker Engine before 27.1.1 allows bypassing AuthZ plugins when using specially crafted API requests with Content-Length header of 0.',
      severity: 'critical',
      cvss_score: 10.0,
      affected_component: 'docker-engine',
      affected_version: '< 27.1.1',
      fixed_version: '27.1.1',
      remediation: 'Update Docker Engine to 27.1.1 or later.',
      patch_guidance: 'apt-get update && apt-get install docker-ce=27.1.1',
      ai_fix: '# Update Docker Engine:\nsudo apt-get update\nsudo apt-get install docker-ce docker-ce-cli containerd.io\n\n# Verify version:\ndocker version',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-41110']
    },
    {
      cve_id: 'CVE-2024-23653',
      title: 'Privilege Escalation in BuildKit',
      description: 'Docker BuildKit before 0.12.5 allows privilege escalation during builds through improper handling of build secrets in multi-stage builds.',
      severity: 'high',
      cvss_score: 8.7,
      affected_component: 'buildkit',
      affected_version: '< 0.12.5',
      fixed_version: '0.12.5',
      remediation: 'Update BuildKit to 0.12.5 or later.',
      patch_guidance: 'Update Docker Desktop or standalone BuildKit installation.',
      ai_fix: '# Use Docker secrets properly:\n# syntax=docker/dockerfile:1\nFROM node:20-slim\n\n# Mount secrets without persisting in layers:\nRUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm install\n\n# Never COPY secrets into the image',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-23653']
    },
  ],

  kubernetes: [
    {
      cve_id: 'CVE-2024-3177',
      title: 'Container Escape via Projected Volumes',
      description: 'Kubernetes before 1.29.4 allows containers to access projected service account tokens from other pods when using shared projected volumes.',
      severity: 'high',
      cvss_score: 8.1,
      affected_component: 'kubernetes',
      affected_version: '< 1.29.4',
      fixed_version: '1.29.4',
      remediation: 'Update Kubernetes to 1.29.4 or later.',
      patch_guidance: 'Upgrade cluster nodes. Review pod security policies.',
      ai_fix: '# Restrict projected volumes in PodSpec:\napiVersion: v1\nkind: Pod\nspec:\n  automountServiceAccountToken: false\n  containers:\n  - name: app\n    securityContext:\n      runAsNonRoot: true\n      readOnlyRootFilesystem: true\n      allowPrivilegeEscalation: false',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-3177']
    },
  ],

  generic: [
    {
      cve_id: 'CVE-2024-50602',
      title: 'Denial of Service in libexpat XML Parser',
      description: 'libexpat before 2.6.4 allows denial of service through XML parsing of documents with many nested element groups.',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'libexpat',
      affected_version: '< 2.6.4',
      fixed_version: '2.6.4',
      remediation: 'Update libexpat to 2.6.4 or later.',
      patch_guidance: 'Update system packages: apt-get update && apt-get install libexpat1',
      ai_fix: '// Set parsing limits:\nXML_Parser parser = XML_ParserCreate(NULL);\nXML_SetElementHandler(parser, startElement, endElement);\n// Set entity expansion limit\nXML_SetBillionLaughsAttackProtectionMaximumAmplification(parser, 100);',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-50602']
    },
    {
      cve_id: 'CVE-2024-45490',
      title: 'Buffer Overflow in libexpat',
      description: 'libexpat before 2.6.3 has a buffer overflow in XML_ParseBuffer when processing large tokens.',
      severity: 'critical',
      cvss_score: 9.8,
      affected_component: 'libexpat',
      affected_version: '< 2.6.3',
      fixed_version: '2.6.3',
      remediation: 'Update libexpat to 2.6.3 or later.',
      patch_guidance: 'Update system packages.',
      ai_fix: '// Use safe parsing with size limits:\n#define MAX_XML_SIZE (10 * 1024 * 1024)  // 10MB\nif (xml_size > MAX_XML_SIZE) {\n    fprintf(stderr, "XML document too large\\n");\n    return -1;\n}',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-45490']
    },
    {
      cve_id: 'CVE-2024-47175',
      title: 'Command Injection in CUPS Printing System',
      description: 'CUPS before 2.4.11 allows command injection through crafted PPD files when processing print jobs.',
      severity: 'high',
      cvss_score: 8.6,
      affected_component: 'cups',
      affected_version: '< 2.4.11',
      fixed_version: '2.4.11',
      remediation: 'Update CUPS to 2.4.11 or later. Disable cupsd if not needed.',
      patch_guidance: 'apt-get update && apt-get install cups',
      ai_fix: '# Disable CUPS if not needed:\nsudo systemctl stop cups\nsudo systemctl disable cups\n\n# Or update:\nsudo apt-get update\nsudo apt-get install cups=2.4.11',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-47175']
    },
    {
      cve_id: 'CVE-2024-6119',
      title: 'DoS in OpenSSL Certificate Name Check',
      description: 'OpenSSL before 3.3.2 is vulnerable to denial of service when checking certificate name constraints with specially crafted certificates.',
      severity: 'medium',
      cvss_score: 5.9,
      affected_component: 'openssl',
      affected_version: '< 3.3.2',
      fixed_version: '3.3.2',
      remediation: 'Update OpenSSL to 3.3.2 or later.',
      patch_guidance: 'Update OpenSSL system package or statically linked library.',
      ai_fix: '# Update OpenSSL:\nsudo apt-get update\nsudo apt-get install openssl libssl-dev\n\n# Verify:\nopenssl version',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-6119']
    },
    {
      cve_id: 'CVE-2024-7264',
      title: 'ASN.1 Parsing Vulnerability in curl',
      description: 'curl before 8.9.1 has an out-of-bounds read when parsing ASN.1 fields in TLS certificates.',
      severity: 'medium',
      cvss_score: 6.5,
      affected_component: 'curl',
      affected_version: '< 8.9.1',
      fixed_version: '8.9.1',
      remediation: 'Update curl to 8.9.1 or later.',
      patch_guidance: 'Update curl system package.',
      ai_fix: '# Update curl:\nsudo apt-get update\nsudo apt-get install curl libcurl4-openssl-dev\n\n# Verify:\ncurl --version',
      references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-7264']
    },
  ],
};

// Language detection patterns
export const LANGUAGE_PATTERNS = {
  javascript: [
    /\.(js|jsx|ts|tsx|mjs|cjs)$/i,
    /package\.json/i,
    /node_modules/i,
    /react|angular|vue|next|express|nest|svelte|nuxt/i,
    /npm|yarn|pnpm|bun/i,
  ],
  python: [
    /\.(py|pyw|pyi)$/i,
    /requirements\.txt/i,
    /setup\.py|pyproject\.toml|Pipfile/i,
    /django|flask|fastapi|pytorch|tensorflow|pandas|numpy/i,
    /pip|conda|poetry/i,
  ],
  java: [
    /\.(java|jar|war|ear|class)$/i,
    /pom\.xml|build\.gradle/i,
    /maven|gradle/i,
    /spring|hibernate|tomcat|wildfly|quarkus/i,
  ],
  go: [
    /\.(go)$/i,
    /go\.mod|go\.sum/i,
    /golang|gin|echo|fiber/i,
  ],
  rust: [
    /\.(rs)$/i,
    /Cargo\.toml|Cargo\.lock/i,
    /rustc|cargo|crate/i,
    /tokio|actix|axum|rocket/i,
  ],
  php: [
    /\.(php|phtml)$/i,
    /composer\.json|composer\.lock/i,
    /laravel|symfony|wordpress|drupal|magento/i,
  ],
  ruby: [
    /\.(rb|erb|rake)$/i,
    /Gemfile|Rakefile/i,
    /rails|sinatra|jekyll|bundler/i,
  ],
  csharp: [
    /\.(cs|csx|csproj|sln)$/i,
    /\.NET|aspnet|nuget/i,
    /dotnet|msbuild/i,
  ],
  docker: [
    /Dockerfile/i,
    /docker-compose/i,
    /\.dockerignore/i,
  ],
  kubernetes: [
    /k8s|kubernetes/i,
    /deployment\.ya?ml|service\.ya?ml/i,
    /helm|kubectl/i,
  ],
};
